// skillList.js
const elementalSkills = [
    {name:"Fire Blast", element:"Fire", power:100, mana:50},
    {name:"Flame Shield", element:"Fire", power:0, mana:40, buff:{armor:20}},
    {name:"Water Wave", element:"Water", power:90, mana:40},
    {name:"Aqua Barrier", element:"Water", power:0, mana:30, buff:{hp:50}},
    {name:"Earthquake", element:"Earth", power:120, mana:60},
    {name:"Stone Skin", element:"Earth", power:0, mana:30, buff:{armor:30}},
    {name:"Wind Slash", element:"Wind", power:80, mana:20},
    {name:"Hurricane", element:"Wind", power:110, mana:50},
    {name:"Lightning Bolt", element:"Lightning", power:100, mana:50},
    {name:"Thunder Storm", element:"Lightning", power:130, mana:60},
    {name:"Ice Spike", element:"Ice", power:80, mana:40},
    {name:"Blizzard", element:"Ice", power:120, mana:60},
    {name:"Fireball", element:"Fire", power:100, mana:50},
    {name:"Steam Cloud", element:"Water", power:50, mana:20},
    {name:"Mud Slide", element:"Earth", power:70, mana:30},
    {name:"Gale Force", element:"Wind", power:90, mana:40},
    {name:"Volt Strike", element:"Lightning", power:100, mana:50},
    {name:"Frost Armor", element:"Ice", power:0, mana:30, buff:{armor:20}},
    {name:"Flame Whip", element:"Fire", power:90, mana:40},
    {name:"Water Jet", element:"Water", power:100, mana:50},
    {name:"Rock Throw", element:"Earth", power:60, mana:20},
    {name:"Wind Cutter", element:"Wind", power:80, mana:30},
    {name:"Static Field", element:"Lightning", power:50, mana:20, debuff:{speed:-10}},
    {name:"Ice Shard", element:"Ice", power:70, mana:30},
    {name:"Lava Burst", element:"Fire", power:120, mana:60},
    {name:"Tsunami", element:"Water", power:130, mana:70},
    {name:"Quicksand", element:"Earth", power:80, mana:40, debuff:{speed:-20}},
    {name:"Whirlwind", element:"Wind", power:100, mana:50},
    {name:"Lightning Cage", element:"Lightning", power:90, mana:40, debuff:{speed:-30}},
    {name:"Frostbite", element:"Ice", power:80, mana:40, debuff:{attack:-10}},
    {name:"Fire Storm", element:"Fire", power:150, mana:80},
    {name:"Rain Dance", element:"Water", power:0, mana:30, buff:{mana:50}},
    {name:"Earth Slam", element:"Earth", power:120, mana:60},
    {name:"Air Blade", element:"Wind", power:100, mana:50},
    {name:"Thunder Clap", element:"Lightning", power:130, mana:60},
    {name:"Ice Wall", element:"Ice", power:0, mana:40, buff:{armor:40}},
    {name:"Inferno", element:"Fire", power:140, mana:70},
    {name:"Wave Crash", element:"Water", power:110, mana:50},
    {name:"Stone Guard", element:"Earth", power:0, mana:30, buff:{armor:50}},
    {name:"Tornado", element:"Wind", power:120, mana:60},
    {name:"Chain Lightning", element:"Lightning", power:150, mana:70},
    {name:"Glacial Spike", element:"Ice", power:130, mana:60},
    {name:"Flare", element:"Fire", power:100, mana:50},
    {name:"Bubble Barrage", element:"Water", power:80, mana:30},
    {name:"Rock Fist", element:"Earth", power:90, mana:40},
    {name:"Wind Gust", element:"Wind", power:70, mana:20},
    {name:"Electric Surge", element:"Lightning", power:120, mana:60},
    {name:"Ice Beam", element:"Ice", power:110, mana:50},
    {name:"Pyroclasm", element:"Fire", power:150, mana:80},
    {name:"Aqua Blast", element:"Water", power:130, mana:70},
    {name:"Boulder Crash", element:"Earth", power:140, mana:80},
    {name:"Cyclone", element:"Wind", power:120, mana:60},
    {name:"Thunderstorm", element:"Lightning", power:160, mana:90},
    {name:"Frost Nova", element:"Ice", power:140, mana:80}
];

const physicalSkills = [
    {name:"Slash", power:50, mana:0},
    {name:"Smash", power:80, mana:10},
    {name:"Quick Strike", power:60, mana:0},
    {name:"Double Hit", power:70, mana:5},
    {name:"Power Punch", power:90, mana:10},
    {name:"Kick", power:60, mana:0},
    {name:"Headbutt", power:80, mana:0},
    {name:"Body Slam", power:100, mana:20},
    {name:"Charge", power:70, mana:0},
    {name:"Spin Attack", power:120, mana:20}
];

module.exports = { elementalSkills, physicalSkills };
